# Generated by Django 3.1.5 on 2021-07-29 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('cases_out', models.IntegerField(blank=True, null=True)),
                ('halfs_out', models.IntegerField(blank=True, null=True)),
                ('sixtels_out', models.IntegerField(blank=True, null=True)),
                ('halfs_in', models.IntegerField(blank=True, null=True)),
                ('sixtels_in', models.IntegerField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('miles_start', models.IntegerField(blank=True, null=True)),
                ('miles_end', models.IntegerField(blank=True, null=True)),
                ('total_stops', models.IntegerField(blank=True, null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Delivery Metrics',
            },
        ),
    ]
