# Generated by Django 3.1.5 on 2021-07-12 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brink_name', models.CharField(max_length=250)),
                ('brink_capacity', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Brink',
                'verbose_name_plural': 'Brinks',
            },
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeast_name', models.CharField(max_length=250)),
                ('yeast_format', models.CharField(choices=[('L', 'Liquid'), ('D', 'Dry')], default='D', max_length=1)),
                ('is_nutrient_required', models.BooleanField(default=True)),
                ('is_harvestable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Yeast',
                'verbose_name_plural': 'Yeasts',
            },
        ),
        migrations.CreateModel(
            name='YeastLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeast_lab_code', models.CharField(max_length=4)),
                ('yeast_lab_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Yeast Lab',
                'verbose_name_plural': 'Yeast Labs',
            },
        ),
        migrations.CreateModel(
            name='YeastPitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(blank=True, max_length=100, null=True)),
                ('generation', models.IntegerField(default=0)),
                ('brink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeast.brink')),
                ('parent_pitch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeast.yeastpitch')),
                ('yeast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeast.yeast')),
            ],
            options={
                'verbose_name': 'Yeast Pitch',
                'verbose_name_plural': 'Yeast Pitches',
            },
        ),
        migrations.AddField(
            model_name='yeast',
            name='yeast_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeast.yeastlab'),
        ),
        migrations.CreateModel(
            name='CellCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('volume', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('pitch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yeast.yeastpitch')),
            ],
            options={
                'verbose_name': 'Cell Count',
                'verbose_name_plural': 'Cell Counts',
            },
        ),
    ]
