# Generated by Django 3.1.5 on 2021-02-27 19:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PL', 'Planning'), ('IP', 'In Process'), ('AR', 'Archive')], default='PL', max_length=2)),
                ('plan_start_day', models.DateField(default=datetime.datetime.now, verbose_name='Planned Start Date')),
                ('qty_turns', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Number of Turns')),
                ('qty_brew_days', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Number of Brew Days')),
                ('is_dh', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is is Dry-Hopped?')),
                ('qty_dh_days', models.IntegerField(blank=True, null=True, verbose_name='How Many DH Days')),
                ('obeer_batch', models.IntegerField(blank=True, null=True, verbose_name='OBeer Batch #')),
                ('obeer_mpn', models.IntegerField(blank=True, null=True, verbose_name='OBeer MPN')),
                ('last_modified_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='BatchSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size_name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Batch Sizes',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Originator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Originators',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_short_code', models.CharField(max_length=4, null=True)),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Partner Types',
            },
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_type', models.CharField(choices=[('FV', 'Fermenter'), ('BT', 'Brite'), ('UT', 'Unitank')], default='FV', max_length=2)),
                ('tank_name', models.CharField(max_length=15)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tanks',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True)),
                ('role', models.CharField(choices=[('HS', 'Hot Side'), ('CS', 'Cold Side'), ('WS', 'Warehouse')], default='HS', max_length=2)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='SchedulePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=25, verbose_name='Pattern Name')),
                ('pattern_total_days', models.IntegerField(null=True, verbose_name='Number of Days in the Pattern')),
                ('offset_yeast_crash', models.IntegerField(null=True, verbose_name='Days Offset for Yeast Crash')),
                ('offset_yeast_harvest', models.IntegerField(null=True, verbose_name='Days Offset for Yeat Harvest')),
                ('offset_dryhop', models.IntegerField(null=True, verbose_name='Days Offset for Dry Hop')),
                ('offset_final_crash', models.IntegerField(null=True, verbose_name='Days Offset for Final Crash')),
                ('offset_transfer', models.IntegerField(null=True, verbose_name='Days Offset for Transfer')),
                ('offset_package', models.IntegerField(null=True, verbose_name='Days Offset for Package')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Schedule Patterns',
                'ordering': ['pattern_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=10)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ownership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.partner')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.producttype')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.partnertype'),
        ),
        migrations.CreateModel(
            name='PackagingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('filled_halfs', models.IntegerField(blank=True, null=True, verbose_name='No. Halfs')),
                ('filled_sixtels', models.IntegerField(blank=True, null=True, verbose_name='No. Sixtels')),
                ('skids_kegs', models.IntegerField(blank=True, null=True, verbose_name='No. Keg Skids')),
                ('filled_cases', models.IntegerField(blank=True, null=True, verbose_name='No. Cases')),
                ('skids_cases', models.IntegerField(blank=True, null=True, verbose_name='No. Case Skids')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who')),
            ],
            options={
                'verbose_name_plural': 'Packaging Runs',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('GR', 'Grain'), ('HP', 'Hops'), ('YT', 'Yeast'), ('OT', 'Other')], default='GR', max_length=2)),
                ('material_name', models.CharField(max_length=100)),
                ('material_obeer_code', models.CharField(blank=True, max_length=25, null=True)),
                ('material_test_field', models.CharField(blank=True, max_length=5, null=True)),
                ('material_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.originator')),
            ],
            options={
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='CarbonationQCEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('carb_vols_brite', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Brite Tank Carb Vols')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who')),
            ],
            options={
                'verbose_name_plural': 'Carbonation QC Entries',
            },
        ),
        migrations.CreateModel(
            name='CanningQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('type', models.CharField(blank=True, choices=[('WT', 'Weight'), ('SH', 'Seam Height'), ('SW', 'Seam Width'), ('BH', 'Body Hook'), ('CH', 'Cover Hook'), ('DO', 'D.O.')], default='WT', max_length=2, null=True, verbose_name='Type')),
                ('measurement', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Measurement')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who')),
            ],
            options={
                'verbose_name_plural': 'Canning QC Data',
            },
        ),
        migrations.CreateModel(
            name='BatchYeastPitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeast_qty', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantity')),
                ('yeast_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source')),
                ('yeast_pitch_temp', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Pitch Temp')),
                ('yeast_pitch_turn', models.IntegerField(blank=True, null=True, verbose_name='Pitch on Turn')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who Pitched?')),
                ('yeast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.material', verbose_name='Yeast')),
            ],
            options={
                'verbose_name_plural': 'Batch Yeast Pitches',
            },
        ),
        migrations.CreateModel(
            name='BatchWortQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(blank=True, null=True, verbose_name='Turn No.')),
                ('temp_mash', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Mash Temp')),
                ('ph_mash', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Mash pH')),
                ('volume_strike', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Stike Water Volume')),
                ('volume_sparge', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Sparge Water Volume')),
                ('volume_preboil', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Pre-boil Volume')),
                ('volume_postboil', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Post-boil Volume')),
                ('extract_first_runnings', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='First Runnings P')),
                ('extract_last_runnings', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Last runnings P')),
                ('extract_preboil', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Pre-Boil P')),
                ('extract_postboil', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Post-Boil P')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('brewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Brewer')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batch Wort QC Data',
            },
        ),
        migrations.CreateModel(
            name='BatchTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('volume_transfer_approx', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Approximate Transfer Volume')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who')),
                ('to_tank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.tank', verbose_name='To Tank')),
            ],
            options={
                'verbose_name_plural': 'Batch Transfers',
            },
        ),
        migrations.CreateModel(
            name='BatchRawMaterialsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_qty', models.CharField(max_length=25, null=True, verbose_name='Quantity')),
                ('material_lot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot Number')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.material', verbose_name='Raw Material')),
            ],
            options={
                'verbose_name_plural': 'Batch Raw Materials Logs',
            },
        ),
        migrations.CreateModel(
            name='BatchPlanDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_date', models.DateField(null=True, verbose_name='Plan Brew Date')),
                ('yeast_crash_date', models.DateField(null=True, verbose_name='Plan Yeast Crash Date')),
                ('yeast_harvest_date', models.DateField(null=True, verbose_name='Plan Yeast Harvest Date')),
                ('dryhop_date', models.DateField(null=True, verbose_name='Plan DH Date')),
                ('final_crash_date', models.DateField(null=True, verbose_name='Plan Final Crash Date')),
                ('transfer_date', models.DateField(null=True, verbose_name='Plan Transfer Date')),
                ('package_date', models.DateField(null=True, verbose_name='Plan Package Date')),
                ('batch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates', to='ebs.batch')),
            ],
            options={
                'verbose_name_plural': 'Batch Plan Dates',
            },
        ),
        migrations.CreateModel(
            name='BatchNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(blank=True, choices=[('PV', 'Private'), ('PB', 'Public'), ('SW', 'Seam Width')], default='PV', max_length=2, null=True, verbose_name='Type')),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batch Notes',
            },
        ),
        migrations.CreateModel(
            name='BatchFermentationQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('extract_apparent', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Apparent Extract')),
                ('sg_real_calculated', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Calculated SG')),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Current pH')),
                ('temp_sv', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp Set Value')),
                ('temp_pv', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp Process Value')),
                ('extract_real', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Calculated Real Extract')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who')),
            ],
            options={
                'verbose_name_plural': 'Batch Fermentation QC Data',
            },
        ),
        migrations.CreateModel(
            name='BatchDOEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_type', models.CharField(choices=[('PE', 'Pre-Fermentation'), ('PT', 'Post-Fermentation'), ('PD', 'Post Dry-Hop'), ('PF', 'Post-Fermentation'), ('TR', 'Transfer')], default='PE', max_length=2, verbose_name='D.O. Measurement Type')),
                ('do_measurement', models.CharField(blank=True, max_length=25, null=True, verbose_name='D.O. Value')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who')),
            ],
            options={
                'verbose_name_plural': 'Batch DO Entries',
            },
        ),
        migrations.CreateModel(
            name='BatchActualDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_date', models.DateField(blank=True, null=True, verbose_name='Actual Brew Date')),
                ('yeast_crash_date', models.DateField(blank=True, null=True, verbose_name='Actual Yeast Crash Date')),
                ('yeast_harvest_date', models.DateField(blank=True, null=True, verbose_name='Actual Yeast Harvest Date')),
                ('dryhop_date', models.DateField(blank=True, null=True, verbose_name='Actual DH Date')),
                ('final_crash_date', models.DateField(blank=True, null=True, verbose_name='Actual Final Crash Date')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='Actual Transfer Date')),
                ('package_date', models.DateField(blank=True, null=True, verbose_name='Actual Package Date')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batch Actual Dates',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Brewer'),
        ),
        migrations.AddField(
            model_name='batch',
            name='last_modified_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='schedule_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.schedulepattern', verbose_name='Schedule Pattern'),
        ),
        migrations.AddField(
            model_name='batch',
            name='target_bt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ebs.tank', verbose_name='Target Brite'),
        ),
        migrations.AddField(
            model_name='batch',
            name='target_fv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ebs.tank', verbose_name='Target Fermenter'),
        ),
        migrations.AddField(
            model_name='batch',
            name='total_batch_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batchsize', verbose_name='Total Volume (BBLs)'),
        ),
    ]
