# Generated by Django 3.1.5 on 2021-02-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchwortqc',
            name='ph_mash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Mash pH'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.originator'),
        ),
    ]
