# Generated by Django 3.1.5 on 2021-01-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ownership',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='PartnerType',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
