# Generated by Django 3.1.5 on 2021-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0002_auto_20210227_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchwortqc',
            name='volume_strike',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Strike Water Volume'),
        ),
    ]
