# Generated by Django 3.1.5 on 2021-03-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0003_auto_20210318_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchnote',
            name='note_type',
            field=models.CharField(blank=True, choices=[('PV', 'Private'), ('PB', 'Public'), ('UM', 'Unlisted Material')], default='PV', max_length=2, null=True, verbose_name='Type'),
        ),
    ]
