# Generated by Django 3.1.5 on 2021-01-25 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebs', '0003_auto_20210123_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='product_days',
        ),
        migrations.AddField(
            model_name='partnertype',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='last_modified_on',
            field=models.DateField(null=True),
        ),
    ]
