# Generated by Django 3.1.5 on 2021-10-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0004_auto_20210319_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrawmaterialslog',
            name='is_dh',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='batchdoentry',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='batchtransfer',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='carbonationqcentry',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
    ]
