# Generated by Django 3.1.5 on 2021-01-27 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebs', '0005_auto_20210127_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_turns', models.IntegerField(null=True)),
                ('qty_brew_days', models.IntegerField(null=True)),
                ('is_dh', models.BooleanField()),
                ('qty_dh_days', models.IntegerField(null=True)),
                ('obeer_batch', models.IntegerField(null=True)),
                ('obeer_mpn', models.IntegerField(null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.product')),
                ('brewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Originator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=25)),
                ('pattern_total_days', models.IntegerField(null=True)),
                ('offset_yeast_crash', models.IntegerField(null=True)),
                ('offset_yeast_harvest', models.IntegerField(null=True)),
                ('offset_dryhop', models.IntegerField(null=True)),
                ('offset_final_crash', models.IntegerField(null=True)),
                ('offset_transfer', models.IntegerField(null=True)),
                ('offset_package', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carb_vols', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('filled_halfs', models.IntegerField(null=True)),
                ('filled_sixtels', models.IntegerField(null=True)),
                ('skids_kegs', models.IntegerField(null=True)),
                ('filled_cases', models.IntegerField(null=True)),
                ('skids_cases', models.IntegerField(null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('GR', 'Grain'), ('HP', 'Hops'), ('YT', 'Yeast'), ('OT', 'Other')], default='GR', max_length=2)),
                ('material_name', models.CharField(max_length=100)),
                ('material_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.originator')),
            ],
        ),
        migrations.CreateModel(
            name='CanningQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_can', models.IntegerField(null=True)),
                ('measure_seam_height', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('measure_seam_width', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('measure_body_hook', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('measure_cover_hook', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('do_can', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchYeastPitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeast_qty', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('yeast_source', models.CharField(max_length=100, null=True)),
                ('yeast_pitch_temp', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('yeast_pitch_turn', models.IntegerField(null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('yeast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.material')),
            ],
        ),
        migrations.CreateModel(
            name='BatchWortQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('temp_mash', models.DecimalField(decimal_places=1, max_digits=4)),
                ('ph_mash', models.DecimalField(decimal_places=1, max_digits=2)),
                ('volume_strike', models.DecimalField(decimal_places=0, max_digits=3)),
                ('volume_sparge', models.DecimalField(decimal_places=0, max_digits=3)),
                ('volume_postboil', models.DecimalField(decimal_places=0, max_digits=3)),
                ('extract_first_runnings', models.DecimalField(decimal_places=1, max_digits=3)),
                ('extract_preboil', models.DecimalField(decimal_places=1, max_digits=3)),
                ('extract_postboil', models.DecimalField(decimal_places=1, max_digits=3)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_transfer_approx', models.DecimalField(decimal_places=1, max_digits=4)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchRawMaterialsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_qty', models.CharField(max_length=25, null=True)),
                ('material_lot', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.material')),
            ],
        ),
        migrations.CreateModel(
            name='BatchPlanDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_date', models.DateField(null=True)),
                ('yeast_crash_date', models.DateField(null=True)),
                ('yeast_harvest_date', models.DateField(null=True)),
                ('dryhop_date', models.DateField(null=True)),
                ('final_crash_date', models.DateField(null=True)),
                ('transfer_date', models.DateField(null=True)),
                ('package_date', models.DateField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
            ],
        ),
        migrations.CreateModel(
            name='BatchFermentationQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('extract_apparent', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('sg_real_calculated', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('temp_sv', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('temp_pv', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('extract_real', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
            ],
        ),
        migrations.CreateModel(
            name='BatchDOEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_type', models.CharField(choices=[('PE', 'Pre-Fermentation'), ('PT', 'Post-Fermentation'), ('PD', 'Post Dry-Hop'), ('PF', 'Post-Fermentation'), ('TR', 'Transfer')], default='PE', max_length=2)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchActualDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_date', models.DateField(null=True)),
                ('yeast_crash_date', models.DateField(null=True)),
                ('yeast_harvest_date', models.DateField(null=True)),
                ('dryhop_date', models.DateField(null=True)),
                ('final_crash_date', models.DateField(null=True)),
                ('transfer_date', models.DateField(null=True)),
                ('package_date', models.DateField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='schedule_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.schedulepattern'),
        ),
        migrations.AddField(
            model_name='batch',
            name='target_bt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ebs.tank'),
        ),
        migrations.AddField(
            model_name='batch',
            name='target_fv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ebs.tank'),
        ),
        migrations.AddField(
            model_name='batch',
            name='total_batch_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batchsize'),
        ),
    ]
