# Generated by Django 3.2.9 on 2022-02-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0006_auto_20211207_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingrun',
            name='line_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Line Can Count'),
        ),
        migrations.AlterField(
            model_name='batchrawmaterialslog',
            name='is_dh',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Cold Side?'),
        ),
    ]
