# Generated by Django 4.0.3 on 2022-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0007_auto_20220203_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_active',
            field=models.BooleanField(default=True),
        ),
    ]
