# Generated by Django 4.0.3 on 2022-06-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0008_material_material_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
