# Generated by Django 3.1.5 on 2021-01-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0008_auto_20210127_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_short_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
