# Generated by Django 3.1.5 on 2021-01-27 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0009_partner_partner_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='plan_start_day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='batch',
            name='obeer_batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='obeer_mpn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_dh_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
