# Generated by Django 4.0.3 on 2023-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0009_staff_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_active',
            field=models.BooleanField(default=True),
        ),
    ]
