# Generated by Django 3.1.5 on 2021-01-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0011_auto_20210127_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchactualdates',
            name='brew_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='dryhop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='final_crash_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='package_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='yeast_crash_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='yeast_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='extract_real',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='sg_real_calculated',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='temp_pv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='temp_sv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='batchplandates',
            name='batch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates', to='ebs.batch'),
        ),
        migrations.AlterField(
            model_name='batchrawmaterialslog',
            name='material_lot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='extract_first_runnings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='extract_postboil',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='extract_preboil',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='ph_mash',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='temp_mash',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='turn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='volume_postboil',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='volume_sparge',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='volume_strike',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.material'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_pitch_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_pitch_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_qty',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='do_can',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='measure_body_hook',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='measure_cover_hook',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='measure_seam_height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='measure_seam_width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='weight_can',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='carb_vols',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='filled_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='filled_halfs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='filled_sixtels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='skids_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='skids_kegs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
