# Generated by Django 4.0.3 on 2023-02-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0011_product_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPackagePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_half_owned', models.IntegerField(default=0)),
                ('kg_half_oneway', models.IntegerField(default=0)),
                ('kg_half_client', models.IntegerField(default=0)),
                ('kg_half_client_oneway', models.IntegerField(default=0)),
                ('kg_sixth_owned', models.IntegerField(default=0)),
                ('kg_sixth_oneway', models.IntegerField(default=0)),
                ('kg_sixth_client', models.IntegerField(default=0)),
                ('kg_sixth_client_oneway', models.IntegerField(default=0)),
                ('cs_16oz', models.IntegerField(default=0)),
                ('cs_12oz', models.IntegerField(default=0)),
                ('cs_500ml', models.IntegerField(default=0)),
                ('cs_750ml', models.IntegerField(default=0)),
                ('package_note', models.TextField(blank=True, max_length=500, null=True)),
                ('batch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
            ],
            options={
                'verbose_name_plural': 'Batch Package Plans',
            },
        ),
    ]
