# Generated by Django 3.1.5 on 2021-01-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0012_auto_20210128_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchwortqc',
            name='turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_qty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
