# Generated by Django 3.1.5 on 2021-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0013_auto_20210128_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdoentry',
            name='do_measurement',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
