# Generated by Django 3.1.5 on 2021-01-28 22:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0014_batchdoentry_do_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='brewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Brewer'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='is_dh',
            field=models.BooleanField(verbose_name='Is is Dry-Hopped?'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='obeer_batch',
            field=models.IntegerField(blank=True, null=True, verbose_name='OBeer Batch #'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='obeer_mpn',
            field=models.IntegerField(blank=True, null=True, verbose_name='OBeer MPN'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='plan_start_day',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Planned Start Date'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_brew_days',
            field=models.IntegerField(null=True, verbose_name='Number of Brew Days'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_dh_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='How Many DH Days'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_turns',
            field=models.IntegerField(null=True, verbose_name='Number of Turns'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='schedule_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.schedulepattern', verbose_name='Schedule Pattern'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='target_bt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ebs.tank', verbose_name='Target Brite'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='target_fv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ebs.tank', verbose_name='Target Fermenter'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_batch_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batchsize', verbose_name='Total Volume (BBLs)'),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='brew_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Brew Date'),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='dryhop_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual DH Date'),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='final_crash_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Final Crash Date'),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='package_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Package Date'),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='transfer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Transfer Date'),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='yeast_crash_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Yeast Crash Date'),
        ),
        migrations.AlterField(
            model_name='batchactualdates',
            name='yeast_harvest_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Yeast Harvest Date'),
        ),
        migrations.AlterField(
            model_name='batchdoentry',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='batchdoentry',
            name='do_measurement',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='D.O. Value'),
        ),
        migrations.AlterField(
            model_name='batchdoentry',
            name='do_type',
            field=models.CharField(choices=[('PE', 'Pre-Fermentation'), ('PT', 'Post-Fermentation'), ('PD', 'Post Dry-Hop'), ('PF', 'Post-Fermentation'), ('TR', 'Transfer')], default='PE', max_length=2, verbose_name='D.O. Measurement Type'),
        ),
        migrations.AlterField(
            model_name='batchdoentry',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='extract_apparent',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Apparent Extract'),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='extract_real',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Calculated Real Extract'),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='ph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Current pH'),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='sg_real_calculated',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Calculated SG'),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='temp_pv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp Process Value'),
        ),
        migrations.AlterField(
            model_name='batchfermentationqc',
            name='temp_sv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp Set Value'),
        ),
        migrations.AlterField(
            model_name='batchplandates',
            name='brew_date',
            field=models.DateField(null=True, verbose_name='Plan Brew Date'),
        ),
        migrations.AlterField(
            model_name='batchplandates',
            name='dryhop_date',
            field=models.DateField(null=True, verbose_name='Plan DH Date'),
        ),
        migrations.AlterField(
            model_name='batchplandates',
            name='final_crash_date',
            field=models.DateField(null=True, verbose_name='Plan Final Crash Date'),
        ),
        migrations.AlterField(
            model_name='batchplandates',
            name='package_date',
            field=models.DateField(null=True, verbose_name='Plan Package Date'),
        ),
        migrations.AlterField(
            model_name='batchplandates',
            name='transfer_date',
            field=models.DateField(null=True, verbose_name='Plan Transfer Date'),
        ),
        migrations.AlterField(
            model_name='batchplandates',
            name='yeast_crash_date',
            field=models.DateField(null=True, verbose_name='Plan Yeast Crash Date'),
        ),
        migrations.AlterField(
            model_name='batchplandates',
            name='yeast_harvest_date',
            field=models.DateField(null=True, verbose_name='Plan Yeast Harvest Date'),
        ),
        migrations.AlterField(
            model_name='batchrawmaterialslog',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.material', verbose_name='Raw Material'),
        ),
        migrations.AlterField(
            model_name='batchrawmaterialslog',
            name='material_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot Number'),
        ),
        migrations.AlterField(
            model_name='batchrawmaterialslog',
            name='material_qty',
            field=models.CharField(max_length=25, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='batchtransfer',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='batchtransfer',
            name='volume_transfer_approx',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Approximate Transfer Volume'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='brewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Brewer'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='extract_first_runnings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='First Runnings P'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='extract_postboil',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Post-Boil P'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='extract_preboil',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Pre-Boil P'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='ph_mash',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Mash pH'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='temp_mash',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Mash Temp'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='turn',
            field=models.IntegerField(blank=True, null=True, verbose_name='Turn No.'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='volume_postboil',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Post-boil Volume'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='volume_sparge',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Sparge Water Volume'),
        ),
        migrations.AlterField(
            model_name='batchwortqc',
            name='volume_strike',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Stike Water Volume'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who Pitched?'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.material', verbose_name='Yeast'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_pitch_temp',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Pitch Temp'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_pitch_turn',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pitch on Turn'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_qty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='yeast_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='do_can',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Can D.O.'),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='measure_body_hook',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Body Hook'),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='measure_cover_hook',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Cover Hook'),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='measure_seam_height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Seam Height'),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='measure_seam_width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Seam Width'),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='canningqc',
            name='weight_can',
            field=models.IntegerField(blank=True, null=True, verbose_name='Can Weight'),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='carb_vols',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Carb Volumes'),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='filled_cases',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. Cases'),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='filled_halfs',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. Halfs'),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='filled_sixtels',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. Sixtels'),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='skids_cases',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. Case Skids'),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='skids_kegs',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. Keg Skids'),
        ),
        migrations.AlterField(
            model_name='packagingrun',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='offset_dryhop',
            field=models.IntegerField(null=True, verbose_name='Days Offset for Dry Hop'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='offset_final_crash',
            field=models.IntegerField(null=True, verbose_name='Days Offset for Final Crash'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='offset_package',
            field=models.IntegerField(null=True, verbose_name='Days Offset for Package'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='offset_transfer',
            field=models.IntegerField(null=True, verbose_name='Days Offset for Transfer'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='offset_yeast_crash',
            field=models.IntegerField(null=True, verbose_name='Days Offset for Yeast Crash'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='offset_yeast_harvest',
            field=models.IntegerField(null=True, verbose_name='Days Offset for Yeat Harvest'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='pattern_name',
            field=models.CharField(max_length=25, verbose_name='Pattern Name'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='pattern_total_days',
            field=models.IntegerField(null=True, verbose_name='Number of Days in the Pattern'),
        ),
    ]
