# Generated by Django 3.1.5 on 2021-02-02 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0015_auto_20210128_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('PL', 'Planning'), ('IP', 'In Process'), ('AR', 'Archive')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='batch',
            name='brewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Brewer'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='is_dh',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is is Dry-Hopped?'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_brew_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Brew Days'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_turns',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Turns'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='schedule_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.schedulepattern', verbose_name='Schedule Pattern'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='target_bt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ebs.tank', verbose_name='Target Brite'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='target_fv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ebs.tank', verbose_name='Target Fermenter'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total_batch_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batchsize', verbose_name='Total Volume (BBLs)'),
        ),
    ]
