# Generated by Django 3.1.5 on 2021-02-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0016_auto_20210202_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulepattern',
            options={'ordering': ['pattern_name'], 'verbose_name_plural': 'Schedule Patterns'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='qty_turns',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Number of Turns'),
        ),
    ]
