# Generated by Django 3.1.5 on 2021-02-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0018_auto_20210204_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchwortqc',
            name='extract_last_runnings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Last runnings P'),
        ),
        migrations.AddField(
            model_name='batchwortqc',
            name='volume_preboil',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Pre-boil Volume'),
        ),
    ]
