# Generated by Django 3.1.5 on 2021-02-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0019_auto_20210208_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='batch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch'),
        ),
    ]
