# Generated by Django 3.1.5 on 2021-02-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebs', '0020_auto_20210210_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canningqc',
            name='do_can',
        ),
        migrations.RemoveField(
            model_name='canningqc',
            name='measure_body_hook',
        ),
        migrations.RemoveField(
            model_name='canningqc',
            name='measure_cover_hook',
        ),
        migrations.RemoveField(
            model_name='canningqc',
            name='measure_seam_height',
        ),
        migrations.RemoveField(
            model_name='canningqc',
            name='measure_seam_width',
        ),
        migrations.RemoveField(
            model_name='canningqc',
            name='weight_can',
        ),
        migrations.RemoveField(
            model_name='packagingrun',
            name='carb_vols',
        ),
        migrations.AddField(
            model_name='batchtransfer',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='batchtransfer',
            name='to_tank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.tank', verbose_name='To Tank'),
        ),
        migrations.AddField(
            model_name='canningqc',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='canningqc',
            name='measurement',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Can Weight'),
        ),
        migrations.AddField(
            model_name='canningqc',
            name='type',
            field=models.CharField(blank=True, choices=[('WT', 'Weight'), ('SH', 'Seam Height'), ('SW', 'Seam Width'), ('BH', 'Body Hook'), ('CH', 'Cover Hook'), ('DO', 'D.O.')], default='WT', max_length=2, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='packagingrun',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='batchyeastpitch',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch'),
        ),
        migrations.CreateModel(
            name='CarbonationQCEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('carb_vols_brite', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Brite Tank Carb Vols')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.staff', verbose_name='Who')),
            ],
            options={
                'verbose_name_plural': 'Carbonation QC Entries',
            },
        ),
    ]
