# Generated by Django 3.1.5 on 2021-02-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0021_auto_20210218_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canningqc',
            name='measurement',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Measurement'),
        ),
    ]
