# Generated by Django 3.1.5 on 2021-02-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebs', '0022_auto_20210218_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(blank=True, choices=[('PV', 'Private'), ('PB', 'Public'), ('SW', 'Seam Width')], default='PV', max_length=2, null=True, verbose_name='Type')),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.batch')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Batch Notes',
            },
        ),
    ]
