# Generated by Django 3.1.5 on 2021-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0023_batchnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_obeer_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
