# Generated by Django 3.1.5 on 2021-02-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0024_material_material_obeer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_test_field',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
