# Generated by Django 3.2.9 on 2022-03-01 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebs', '0007_auto_20220203_1356'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_detail', models.CharField(blank=True, max_length=256, null=True)),
                ('label_abv', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True)),
                ('tap_regulator_psi', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True)),
                ('public_tasting_notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('may_also_like', models.TextField(blank=True, max_length=1000, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='svc/%Y/%m/%d/')),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.product', verbose_name='Product')),
            ],
        ),
    ]
