# Generated by Django 4.0.3 on 2023-01-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0010_alter_product_options_partner_partner_active'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productserviceinfo',
            name='product',
            field=models.ForeignKey(blank=True, limit_choices_to={'ownership_id': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebs.product', verbose_name='Product'),
        ),
    ]
