# Generated by Django 3.2.9 on 2021-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_code', models.CharField(default='X', max_length=5)),
                ('mod_name', models.CharField(max_length=25)),
                ('mod_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Models',
            },
        ),
    ]
