# Generated by Django 3.2.9 on 2021-12-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blmodule',
            options={'verbose_name_plural': 'Modules'},
        ),
        migrations.AddField(
            model_name='blmodule',
            name='mod_order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
