# Generated by Django 3.2.9 on 2021-12-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20211207_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blmodule',
            options={'verbose_name': 'BL1 Module', 'verbose_name_plural': 'BL1 Modules'},
        ),
        migrations.AddField(
            model_name='blmodule',
            name='mod_url_suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
