# Generated by Django 3.1.5 on 2021-05-19 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_group', models.CharField(choices=[('OF', 'Off-Premise'), ('ON', 'On-Premise')], default='OF', max_length=2)),
                ('account_type', models.CharField(choices=[('P', 'Prospect'), ('A', 'Acquisition'), ('M', 'Maintenance'), ('D', 'Dead')], default='M', max_length=1)),
                ('obeer_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ale_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_week_monday', models.DateField(blank=True, null=True)),
                ('schedule_week', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('S', 'Sales'), ('C', 'Courtesy'), ('I', 'Inventory'), ('X', 'Collection')], max_length=1, null=True)),
                ('method', models.CharField(blank=True, choices=[('P', 'Phone'), ('T', 'Text Message'), ('E', 'Email'), ('V', 'VISIT')], max_length=1, null=True)),
                ('samples', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('RST', 'Radio Silent'), ('ODR', 'Order'), ('LWP', 'Wrong Person'), ('LNA', 'Later, Not Available'), ('LNS', 'Later, No Space'), ('LPD', 'Later, Diff Product')], max_length=3, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('follow_up_required', models.BooleanField(default=True)),
                ('follow_up_delay', models.IntegerField(choices=[(0, 'This Week'), (1, 'Next Week'), (2, 'In Two Weeks'), (3, 'In Three Weeks'), (4, 'In A Month'), (12, 'In Three Months'), (26, 'In Six Months')], default=1)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.account')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_call', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.call')),
            ],
            options={
                'verbose_name_plural': 'Calls',
            },
        ),
    ]
