# Generated by Django 3.1.5 on 2021-10-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Territories',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='account_territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.territory'),
        ),
    ]
