# Generated by Django 4.0.3 on 2022-09-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_auto_20211207_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasting_date', models.DateField(blank=True, null=True)),
                ('estimated_interations', models.IntegerField()),
                ('estimated_attributable_units_sold', models.IntegerField()),
                ('estimated_units_used', models.IntegerField()),
                ('sentiment', models.CharField(blank=True, choices=[('S', 'Smiley Face'), ('O', 'Okay Face'), ('F', 'Frowny Face')], max_length=1, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('last_modified_on', models.DateField(auto_now=True)),
                ('at_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.account')),
                ('last_modified_by', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
